### ISSUE TITLE
Cross reference between header files (circular dependency)

### ISSUE THREAD

**Issue by laqieer** [StanHash/fe6#6]
unit.h includes `common.h`
https://github.com/StanHash/fe6/blob/3b1383eaf3b75335ec6e6196ac5f8f9fb2cf7672/include/unit.h#L3
common.h includes `unknown_objects.h`
https://github.com/StanHash/fe6/blob/3b1383eaf3b75335ec6e6196ac5f8f9fb2cf7672/include/common.h#L27
`unknown_objects.h` contains `struct UnitInfo` (introduced in https://github.com/StanHash/fe6/commit/638f7a168d2a9cfa73a3cccb67cb7f1b16a0d530)
https://github.com/StanHash/fe6/blob/3b1383eaf3b75335ec6e6196ac5f8f9fb2cf7672/include/unknown_objects.h#L236
`struct UnitInfo` is defined in `unit.h`
https://github.com/StanHash/fe6/blob/3b1383eaf3b75335ec6e6196ac5f8f9fb2cf7672/include/unit.h#L240
That introduces reference circle: `unit.h`->`common.h`->`unknown_objects.h`->`unit.h`
```
ai_080326C4.c
In file included from /Users/laqieer/Projects/FEHRR/include/decomp/include/common.h:27,
                 from /Users/laqieer/Projects/FEHRR/include/decomp/include/unit.h:3,
                 from /Users/laqieer/Projects/FEHRR/source/ai_080326C4.c:2:
/Users/laqieer/Projects/FEHRR/include/decomp/include/unknown_objects.h:236:30: error: array type has incomplete element type 'struct UnitInfo'
  236 | extern struct UnitInfo const gUnk_086876AC[];
      |                              ^~~~~~~~~~~~~
/Users/laqieer/Projects/FEHRR/include/decomp/include/unknown_objects.h:237:30: error: array type has incomplete element type 'struct UnitInfo'
  237 | extern struct UnitInfo const gUnk_086876CC[];
      |                              ^~~~~~~~~~~~~
/Users/laqieer/Projects/FEHRR/include/decomp/include/unknown_objects.h:238:30: error: array type has incomplete element type 'struct UnitInfo'
  238 | extern struct UnitInfo const gUnk_086876EC[];
      |                              ^~~~~~~~~~~~~
/Users/laqieer/Projects/FEHRR/include/decomp/include/unknown_objects.h:239:30: error: array type has incomplete element type 'struct UnitInfo'
  239 | extern struct UnitInfo const gUnk_0868770C[];
      |                              ^~~~~~~~~~~~~
/Users/laqieer/Projects/FEHRR/include/decomp/include/unknown_objects.h:240:30: error: array type has incomplete element type 'struct UnitInfo'
  240 | extern struct UnitInfo const gUnk_0868772C[];
      |                              ^~~~~~~~~~~~~
/Users/laqieer/Projects/FEHRR/include/decomp/include/unknown_objects.h:241:30: error: array type has incomplete element type 'struct UnitInfo'
  241 | extern struct UnitInfo const gUnk_0868774C[];
      |                              ^~~~~~~~~~~~~
/Users/laqieer/Projects/FEHRR/include/decomp/include/unknown_objects.h:242:30: error: array type has incomplete element type 'struct UnitInfo'
  242 | extern struct UnitInfo const gUnk_0868776C[];
      |                              ^~~~~~~~~~~~~
/Users/laqieer/Projects/FEHRR/include/decomp/include/unknown_objects.h:243:30: error: array type has incomplete element type 'struct UnitInfo'
  243 | extern struct UnitInfo const gUnk_0868778C[];
      |                              ^~~~~~~~~~~~~
make[1]: *** [ai_080326C4.o] Error 1
make: *** [build] Error 2
```
